version: '3'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  web_app:
    build: .
    command: bash start.sh
    ports:
      - '3337:3337'
    volumes:
      - '.:/spotlight'
    volumes:
      - box:/box
    environment:
      - SKIP_PREFLIGHT_CHECK=true
    depends_on:
      - postgres
      - box

  box:
    image: busybox
    volumes:
      - /box
 
volumes:
  postgres:
  box:
