version: '3'

services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=safe

  web_app:
    build: .
    command: bash start.sh
    ports:
      - '3337:3337'
    volumes:
      - '.:/spotlight'
    volumes:
      - box:/box
    depends_on:
      - postgres
    environment:
      - SKIP_PREFLIGHT_CHECK=true

  box:
    image: busybox
    volumes:
      - /box
 
volumes:
  postgres:
  box:
