default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['db_user']  || 'root' %>
  password: <%= ENV['db_pass'] %>
  port: <%= ENV['db_port']  || 5432 %>
  host: <%= ENV['db_host']  || 'postgres' %>

development:
  <<: *default
  database: spotlight_development

test:
  <<: *default
  database: spotlight_test

production:
  <<: *default
  database: spotlight_production
